version: "3.9"
services:
  agora-ui:
    image: agora-ui
    networks:
      new:
        aliases:
          - agora-ui
    build: .
  proxy:
    container_name: agora-proxy
    image: agora-ui-proxy
    ports:
        - "443:443"
        - "80:80"
    depends_on: 
        - agora-ui
    networks:
      new:
        aliases:
          - agora-ui
    build: ./dev-proxy
networks:
  new: