export const inviteConstants  = {

    CREATE_REQUEST: 'CREATE_INVITE_REQUEST',
    CREATE_SUCCESS: 'CREATE_INVITE_SUCCESS',
    CREATE_FAILURE: 'CREATE_INVITE_FAILURE',

    DELETE_REQUEST: 'DELETE_INVITE_REQUEST',
    DELETE_SUCCESS: 'DELETE_INVITE_SUCCESS',
    DELETE_FAILURE: 'DELETE_INVITE_FAILURE'

}