export const meetingConstants = {

    CREATE_REQUEST :  'MEETING_CREATE_REQUEST',
    CREATE_SUCCESS : 'MEETING_CREATE_SUCCESS',
    CREATE_FAILURE : 'MEETING_CREATE_FAILURE',

    GET_MEETINGS_REQUEST : 'GET_MEETINGS_REQUEST',
    GET_MEETINGS_SUCCESS : 'GET_MEETINGS_SUCCESS',
    GET_MEETINGS_FAILURE : 'GET_MEETINGS_FAILURE',

    DELETE_MEETING : 'DELETE_MEETING',


    GET_MEETING_REQUEST : 'GET_MEETING_REQUEST',
    GET_MEETING_SUCCESS : 'GET_MEETING_SUCCESS',
    GET_MEETING_FAILURE : 'GET_MEETING_FAILURE',

    ADD_PARTICIPANT : 'ADD_MEETING_PARTICIPANT',
    DELETE_PARTICIPANT : 'DELETE_MEETING_PARTICIPANT'


}