export const oauthConstants = {

    AUTHORIZATION_REQUEST :  'OAUTH_AUTHORIZATION_REQUEST',
    AUTHORIZATION_SUCCESS : 'OAUTH_AUTHORIZATION_SUCCESS',
    AUTHORIZATION_FAILURE : 'OAUTH_AUTHORIZATION_FAILURE',

    ACCESS_REQUEST :  'OAUTH_AUTHORIZATION_REQUEST',
    ACCESS_SUCCESS : 'OAUTH_AUTHORIZATION_SUCCESS',
    ACCESS_FAILURE : 'OAUTH_AUTHORIZATION_FAILURE',

    CHECK_AUTHORIZATION : 'OAUTH_CHECK_AUTHORIZATION',
}